DROP TABLE business_rule;
create table business_rule (
    id bigint generated by default as identity,
    name varchar(255) not null,
    rule_type enum ('Enrichment','Routing') not null,
    condition varchar(255) not null,
    action varchar(255) not null,
    priority integer not null,
    active boolean not null,
    created_at timestamp(6),
    created_by bigint,
    updated_at timestamp(6),
    updated_by bigint,
    primary key (id)
);
insert into business_rule (name , rule_type , condition , action , priority,active)
values (
  'First Value Rule',
  'Enrichment',
  'amount > 500',
  'transactionType = ''HIGH_VALUE''',
  1,
  true
);
insert into business_rule (name , rule_type , condition , action , priority,active)
values (
    'Second Value Rule',
    'Enrichment',
    'amount > 500',
    'transactionType = ''HIGH_VALUE''',
    2 ,
    true
);
insert into business_rule (name , rule_type , condition , action , priority,active)
values (
    'Third Value Rule',
    'Enrichment',
    'amount > 500',
    'transactionType = ''HIGH_VALUE''',
    3 ,
    true
);
insert into business_rule (name , rule_type , condition , action , priority,active)
values (
    'Fourth Value Rule',
    'Enrichment',
    'amount > 500',
    'transactionType = ''HIGH_VALUE''',
    4 ,
    true
);
insert into business_rule (name , rule_type , condition , action , priority,active)
values (
    'Six Value Rule',
    'Routing',
    'currency == ''USD''',
    'status = ''ROUTED''',
    1 ,
    true
);
